// JEE/NEET topic-wise syllabus map. subject -> chapter -> topics[].
// Curated from latest JEE/NEET PYQ-relevant micro-topics.

export type SyllabusMap = Record<string, Record<string, string[]>>;

export const SYLLABUS: SyllabusMap = {
  Physics: {
    'Units and Measurements': [
      'Dimensional formulas of physical constants (G, ε₀, μ₀, h)',
      'Principle of Homogeneity and applications',
      'Conversion of units using dimensional analysis',
      'Significant figures and rounding off',
      'Absolute, relative, and percentage error',
      'Combination of errors in sums, products, and powers',
      'Vernier Callipers — least count and zero error',
      'Screw Gauge — pitch and least count',
    ],
    'Motion in a Straight Line': [
      'Instantaneous velocity and acceleration',
      'Kinematic equations for constant acceleration',
      'Analysis of x-t, v-t, a-t graphs',
      'Relative velocity in 1D',
      'Motion under gravity — time of ascent and descent',
    ],
    'Motion in a Plane': [
      'Vector addition, subtraction, and resolution',
      'Dot and Cross products',
      'Projectile motion — time of flight, max height, range',
      'Equation of trajectory and range on inclined plane',
      'Uniform circular motion',
      'Relative velocity — rain-man and river-boat problems',
    ],
    'Laws of Motion': [
      'Newton’s Second Law (F=ma)',
      'Impulse-Momentum Theorem',
      'Conservation of linear momentum',
      'Equilibrium of concurrent forces (Lami’s Theorem)',
      'Free Body Diagrams with pulleys and blocks',
      'Friction — static, limiting, kinetic',
      'Angle of friction and angle of repose',
      'Block on inclined plane with friction',
      'Centripetal and centrifugal forces',
      'Banking of roads and bending of cyclist',
    ],
    'Work, Energy and Power': [
      'Work done by constant and variable forces',
      'Kinetic energy and Work-Energy Theorem',
      'Gravitational and Spring PE',
      'Conservation of mechanical energy',
      'Instantaneous and average power',
      'Elastic and inelastic collisions in 1D and 2D',
      'Coefficient of restitution',
    ],
    'System of Particles and Rotational Motion': [
      'Centre of mass — discrete and continuous systems',
      'Motion of COM and conservation of momentum',
      'Torque and angular momentum (L=Iω)',
      'Parallel and perpendicular axis theorems',
      'MOI of standard bodies (ring, disc, rod, sphere, cylinder)',
      'Radius of gyration',
      'Rolling motion — KE and acceleration on incline',
    ],
    Gravitation: [
      'Newton’s Law of Gravitation (vector form)',
      'Variation of g with altitude, depth, rotation',
      'Gravitational PE and gravitational potential',
      'Escape velocity and orbital velocity',
      'Kepler’s laws of planetary motion',
    ],
    'Mechanical Properties of Solids': [
      'Stress-strain curve and Hooke’s Law',
      'Young’s, Bulk and Rigidity moduli',
      'Elastic PE in a stretched wire',
    ],
    'Mechanical Properties of Fluids': [
      'Pascal’s Law and Hydraulic Lift',
      'Variation of pressure with depth and Buoyancy',
      'Viscosity — Stokes Law and terminal velocity',
      'Bernoulli’s Principle — Venturimeter, Torricelli',
      'Surface Tension — excess pressure in drops, capillary rise',
    ],
    'Thermal Properties of Matter': [
      'Linear, areal and volumetric thermal expansion',
      'Specific heat capacity and calorimetry',
      'Latent heat and phase changes',
      'Heat transfer — conduction, convection, radiation',
    ],
    Thermodynamics: [
      'Zeroth and First Law of Thermodynamics',
      'Isothermal, adiabatic, isobaric and isochoric processes',
      'Cp, Cv and their relation',
      'Heat engines and efficiency',
      'Refrigerators and COP',
      'Carnot cycle',
      'Second law and entropy basics',
    ],
    'Kinetic Theory of Gases': [
      'Ideal gas equation and assumptions',
      'Mean, RMS and most probable speeds',
      'Degrees of freedom and equipartition of energy',
      'Mean free path',
    ],
    Oscillations: [
      'SHM — displacement, velocity, acceleration',
      'Energy in SHM',
      'Spring oscillations and series/parallel combinations',
      'Simple pendulum and physical pendulum',
      'Damped and forced oscillations, resonance',
    ],
    Waves: [
      'Transverse and longitudinal waves',
      'Speed of waves on a string and in gases',
      'Superposition, interference and standing waves',
      'Beats and beat frequency',
      'Doppler effect',
    ],
    'Electric Charges and Fields': [
      'Coulomb’s Law and superposition',
      'Electric field due to point charges, dipoles and continuous distributions',
      'Gauss’s Law and applications (sphere, cylinder, plane)',
      'Electric flux',
    ],
    'Electrostatic Potential and Capacitance': [
      'Electric potential and PE of a system',
      'Equipotential surfaces',
      'Capacitor — parallel plate, with dielectric',
      'Series/parallel combinations of capacitors',
      'Energy stored in a capacitor',
    ],
    'Current Electricity': [
      'Ohm’s Law, drift velocity, mobility',
      'Resistivity and temperature dependence',
      'Kirchhoff’s laws and Wheatstone bridge',
      'Meter bridge and potentiometer',
      'Cells — EMF, internal resistance, combinations',
    ],
    'Moving Charges and Magnetism': [
      'Magnetic force on moving charge — Lorentz force',
      'Biot-Savart Law and Ampere’s Law',
      'Magnetic field due to a straight wire, loop, solenoid',
      'Cyclotron',
      'Force between parallel currents',
      'Galvanometer — conversion to ammeter and voltmeter',
    ],
    'Magnetism and Matter': [
      'Bar magnet and magnetic dipole moment',
      'Earth’s magnetism',
      'Dia-, para-, and ferromagnetism',
      'Hysteresis loop',
    ],
    'Electromagnetic Induction': [
      'Faraday’s Law and Lenz’s Law',
      'Motional EMF',
      'Self and mutual induction',
      'Energy stored in an inductor',
      'Eddy currents',
    ],
    'Alternating Current': [
      'AC circuits — R, L, C and combinations',
      'Phasors and impedance',
      'LCR series resonance',
      'Power in AC, power factor',
      'Transformer',
    ],
    'Electromagnetic Waves': [
      'Maxwell’s equations (qualitative)',
      'EM wave properties and energy',
      'EM spectrum and applications',
    ],
    'Ray Optics and Optical Instruments': [
      'Reflection at spherical mirrors — mirror formula',
      'Refraction and Snell’s Law',
      'Total internal reflection and applications',
      'Lens formula and lensmaker’s equation',
      'Combination of lenses, power',
      'Prism — dispersion and angular deviation',
      'Microscope and telescope',
    ],
    'Wave Optics': [
      'Huygens’ principle',
      'Young’s double slit experiment',
      'Single slit diffraction',
      'Polarisation — Brewster’s law, Malus’ law',
    ],
    'Dual Nature of Radiation and Matter': [
      'Photoelectric effect and Einstein’s equation',
      'de Broglie wavelength',
      'Davisson-Germer experiment',
    ],
    Atoms: [
      'Bohr model — energy levels and spectra',
      'Hydrogen spectrum series',
      'Rutherford scattering',
    ],
    Nuclei: [
      'Mass defect and binding energy per nucleon',
      'Radioactivity — α, β, γ decay',
      'Half-life and mean life',
      'Nuclear fission and fusion',
    ],
    'Semiconductor Electronics': [
      'Energy bands — metals, insulators, semiconductors',
      'P-N junction — forward and reverse bias',
      'Diode as rectifier (half and full wave)',
      'Logic gates — OR, AND, NOT, NAND, NOR',
    ],
  },
  Chemistry: {
    'Some Basic Concepts of Chemistry': [
      'Mole concept, stoichiometry, limiting reagent',
      'Concentration terms — molarity, molality, normality, mole fraction',
      'Empirical and molecular formula',
    ],
    'Structure of Atom': [
      'Quantum numbers (n, l, m, s)',
      'Electronic configuration — Aufbau, Pauli, Hund’s Rule',
      'Bohr model and hydrogen spectrum',
      'de Broglie wavelength and Heisenberg’s uncertainty',
    ],
    'Classification of Elements and Periodicity': [
      'Trends in atomic and ionic radius',
      'Ionisation enthalpy and electron gain enthalpy',
      'Electronegativity trends',
      'Diagonal relationship',
    ],
    'Chemical Bonding and Molecular Structure': [
      'VSEPR theory — molecular geometry',
      'Hybridisation (sp, sp², sp³, sp³d, sp³d²)',
      'Molecular Orbital Theory — bond order, magnetic behavior',
      'Hydrogen bonding',
      'Resonance and formal charge',
    ],
    'States of Matter': [
      'Ideal gas equation and Dalton’s Law',
      'Real gases — van der Waals equation',
      'Critical phenomena',
    ],
    'Thermodynamics (Chemistry)': [
      'First Law — enthalpy and internal energy',
      'Hess’s Law',
      'Entropy and Gibbs free energy (ΔG) for spontaneity',
      'Bond enthalpy and lattice energy',
    ],
    Equilibrium: [
      'Law of mass action — Kp and Kc',
      'Le Chatelier’s Principle',
      'Ionic equilibrium — pH, buffer solutions',
      'Solubility product (Ksp)',
      'Acid–base concepts',
    ],
    'Redox Reactions': [
      'Oxidation number rules',
      'Balancing redox reactions (oxidation number / half-reaction)',
      'Standard electrode potentials',
    ],
    Solutions: [
      'Raoult’s Law and ideal/non-ideal solutions',
      'Colligative properties',
      'Van’t Hoff factor',
      'Abnormal molecular mass',
    ],
    Electrochemistry: [
      'Nernst equation',
      'Electrochemical series',
      'Faraday’s Laws of Electrolysis',
      'Molar conductivity and Kohlrausch’s law',
      'Galvanic and electrolytic cells',
    ],
    'Chemical Kinetics': [
      'Order and molecularity',
      'First order — integrated rate law and half-life',
      'Arrhenius equation and activation energy',
      'Effect of catalyst and temperature',
    ],
    'The p-Block Elements (Group 15-18)': [
      'Oxoacids of phosphorus, sulphur, halogens',
      'Allotropes and anomalous behavior',
      'Interhalogens and noble gas compounds',
    ],
    'The d- and f-Block Elements': [
      'Lanthanoid contraction',
      'Variable oxidation states',
      'Magnetic properties and color',
      'KMnO₄ and K₂Cr₂O₇ — preparation and reactions',
    ],
    'Coordination Compounds': [
      'IUPAC nomenclature of complexes',
      'Isomerism — geometrical, optical, ionisation, linkage',
      'Crystal Field Theory — splitting in octahedral and tetrahedral fields',
      'Stability of complexes',
    ],
    'Organic Chemistry — Basic Principles & Techniques': [
      'Inductive, resonance and hyperconjugation effects',
      'Stability of carbocations, carbanions and free radicals',
      'Nucleophilic vs electrophilic substitution mechanisms',
      'Methods of purification of organic compounds',
    ],
    Hydrocarbons: [
      'Alkanes — preparation and reactions',
      'Markovnikov and anti-Markovnikov addition',
      'Alkynes — acidity and reactions',
      'Aromatic hydrocarbons — electrophilic substitution',
    ],
    'Haloalkanes and Haloarenes': [
      'SN1 and SN2 mechanisms',
      'Elimination reactions — E1, E2',
      'Reactions of haloarenes',
    ],
    'Alcohols, Phenols and Ethers': [
      'Reimer-Tiemann reaction',
      'Kolbe’s reaction',
      'Williamson ether synthesis',
      'Acidity of alcohols vs phenols',
    ],
    'Aldehydes, Ketones and Carboxylic Acids': [
      'Aldol condensation',
      'Cannizzaro reaction',
      'Wittig and Clemmensen reactions',
      'Acidity of carboxylic acids',
    ],
    Amines: [
      'Hoffmann bromamide degradation',
      'Carbylamine reaction',
      'Diazonium salts and reactions',
      'Basicity of amines',
    ],
    Biomolecules: [
      'Glucose — open chain and cyclic structure',
      'Amino acids — zwitterion, peptide bond',
      'DNA and RNA — bases and structure',
    ],
  },
  Mathematics: {
    'Sets': ['Types of sets', 'Operations on sets', 'Venn diagrams'],
    'Relations and Functions': [
      'Types of relations — equivalence',
      'Composite functions and inverse functions',
      'Domain, range, and graphs',
    ],
    'Trigonometric Functions': [
      'Trig identities and equations',
      'Inverse trigonometric functions basics',
      'Heights and distances',
    ],
    'Complex Numbers and Quadratic Equations': [
      'Argand plane and modulus-argument form',
      'Euler’s form and De Moivre’s theorem',
      'Cube roots of unity',
      'Location of roots and common roots',
    ],
    'Permutations and Combinations': [
      'Linear and circular arrangements',
      'Combinations with restrictions',
      'Derangements',
    ],
    'Binomial Theorem': [
      'General term and middle term',
      'Independent term',
      'Properties of binomial coefficients',
    ],
    'Sequences and Series': [
      'AP, GP, HP and AGP',
      'AM-GM-HM inequality',
      'Summation of special series (Σn, Σn², Σn³)',
    ],
    'Straight Lines': [
      'Distance between parallel lines',
      'Family of lines',
      'Angle bisectors',
    ],
    'Conic Sections': [
      'Parabola — focal chord, latus rectum',
      'Ellipse — eccentricity, director circle',
      'Hyperbola — asymptotes, conjugate hyperbola',
    ],
    'Limits and Derivatives': [
      'Standard limits and L’Hopital’s Rule',
      'Differentiation rules and chain rule',
      'Logarithmic differentiation',
    ],
    Probability: [
      'Conditional probability',
      'Bayes’ theorem',
      'Bernoulli trials and binomial distribution',
    ],
    Matrices: [
      'Types of matrices and operations',
      'Inverse by adjoint method',
      'Elementary row operations',
    ],
    Determinants: [
      'Properties of determinants',
      'Cramer’s Rule',
      'Area of triangle and consistency of equations',
    ],
    'Continuity and Differentiability': [
      'Continuity at a point and on an interval',
      'Differentiability and chain rule',
      'Rolle’s and Mean Value theorems',
    ],
    'Application of Derivatives': [
      'Tangents and normals',
      'Maxima and minima',
      'Increasing/decreasing functions',
      'Approximations',
    ],
    Integrals: [
      'Integration by substitution',
      'Integration by parts',
      'Integration using partial fractions',
      'Properties of definite integrals',
      'Leibnitz Rule',
    ],
    'Application of Integrals': [
      'Area under curves',
      'Area between two curves',
    ],
    'Differential Equations': [
      'Variable separable',
      'Linear differential equations',
      'Homogeneous differential equations',
    ],
    'Vector Algebra': [
      'Dot and cross products',
      'Scalar and vector triple products',
      'Applications to geometry',
    ],
    'Three Dimensional Geometry': [
      'Direction cosines and ratios',
      'Equation of line and plane',
      'Shortest distance between skew lines',
      'Angle between two planes',
    ],
  },
  Biology: {
    'Biological Classification': [
      'Monera — characteristics and examples',
      'Protista — characteristics and examples',
      'Fungi — classification and reproduction',
      'Five kingdom classification',
    ],
    'Animal Kingdom': [
      'Non-chordates — classification with examples',
      'Chordates — classification up to class',
      'Salient features and distinguishing characters',
    ],
    'Anatomy of Flowering Plants': [
      'Tissue systems — epidermal, ground, vascular',
      'Anatomy of dicot and monocot stem',
      'Secondary growth in dicot stems',
    ],
    'Cell Cycle and Cell Division': [
      'Phases of cell cycle',
      'Mitosis — stages and significance',
      'Meiosis — Prophase I sub-stages',
    ],
    'Principles of Inheritance and Variation': [
      'Mendel’s laws',
      'Dihybrid cross and test cross',
      'Pedigree analysis',
      'Chromosomal disorders',
    ],
    'Molecular Basis of Inheritance': [
      'DNA replication',
      'Transcription — promoter and terminator',
      'Translation and genetic code',
      'Lac operon',
    ],
    'Body Fluids and Circulation': [
      'Cardiac cycle',
      'ECG waves',
      'Double circulation',
      'Blood groups and clotting',
    ],
    'Excretory Products and Their Elimination': [
      'Mechanism of urine formation',
      'Counter-current mechanism',
      'Regulation of kidney function',
    ],
    'Neural Control and Coordination': [
      'Nerve impulse conduction',
      'Reflex arc',
      'Synapse and synaptic transmission',
    ],
    'Photosynthesis in Higher Plants': [
      'Cyclic and non-cyclic photophosphorylation',
      'C3 vs C4 pathway',
      'Photorespiration',
      'Factors affecting photosynthesis',
    ],
    'Respiration in Plants': [
      'Glycolysis',
      'Krebs cycle',
      'Electron transport system',
      'Respiratory quotient',
    ],
    'Organisms and Populations': [
      'Mutualism, competition and predation',
      'Population growth models',
      'Population attributes',
    ],
    Ecosystem: [
      'Energy flow in ecosystem',
      'Ecological pyramids',
      'Nutrient cycling — carbon and phosphorus',
    ],
    'Biodiversity and Conservation': [
      'In-situ and ex-situ conservation',
      'Hotspots of biodiversity',
      'IUCN red list categories',
    ],
  },
};

/* ============================================================
   OFFICIAL NTA JEE (Main + Advanced) COVERAGE — remaining chapters
   Merged into SYLLABUS so topic-wise tests & PDFs match the real syllabus.
   ============================================================ */
const ADDITIONAL: SyllabusMap = {
  Physics: {
    'Gravitation': [
      'Universal law of gravitation and gravitational constant',
      'Variation of g with altitude, depth and rotation of earth',
      'Gravitational potential energy and potential',
      'Escape velocity and orbital velocity',
      'Satellites — time period, energy, binding energy',
      'Geostationary and polar satellites',
      "Kepler's three laws of planetary motion",
    ],
    'Thermodynamics (Physics)': [
      'Zeroth law and concept of temperature',
      'First law of thermodynamics and internal energy',
      'Isothermal, adiabatic, isobaric and isochoric processes',
      'Work done in P-V diagrams and cyclic processes',
      'Specific heat capacities Cp, Cv and Mayer relation',
      'Second law, heat engines, efficiency and refrigerators',
      'Carnot engine and coefficient of performance',
    ],
    'Oscillations': [
      'SHM — displacement, velocity, acceleration equations',
      'Energy in SHM (kinetic, potential, total)',
      'Simple pendulum and time period variations',
      'Spring-mass systems — series and parallel springs',
      'Damped, forced oscillations and resonance',
    ],
    'Waves': [
      'Transverse and longitudinal wave equations',
      'Speed of wave on a string and in a gas (Newton-Laplace)',
      'Superposition, interference and beats',
      'Standing waves in strings and organ pipes',
      'Harmonics, overtones and end correction',
      'Doppler effect in sound',
    ],
    'Atoms': [
      'Rutherford scattering and distance of closest approach',
      'Bohr model — radius, velocity, energy of orbits',
      'Hydrogen spectral series (Lyman, Balmer, Paschen)',
      'de Broglie explanation of Bohr quantisation',
    ],
    'Nuclei': [
      'Composition, size and density of nucleus',
      'Mass defect and binding energy per nucleon curve',
      'Radioactivity — alpha, beta, gamma decay',
      'Law of radioactive decay, half-life and mean life',
      'Nuclear fission and fusion, energy release',
    ],
    'Experimental Skills': [
      'Vernier callipers and screw gauge measurements',
      'Simple pendulum — determination of g',
      'Metre scale — mass by principle of moments',
      'Youngs modulus by Searles apparatus',
      'Surface tension and viscosity by terminal velocity',
      'Resistivity by metre bridge and Ohms law',
      'Potentiometer — comparison of EMF and internal resistance',
      'Focal length of concave mirror and convex lens',
      'Refractive index using glass slab and prism',
      'Characteristic curves of p-n junction diode and Zener diode',
      'Identification of components using multimeter',
    ],
  },
  Chemistry: {
    'Chemical Thermodynamics': [
      'System, surroundings, state functions and extensive/intensive properties',
      'First law — internal energy, enthalpy, heat capacity',
      'Hess law and enthalpies of formation, combustion, neutralisation',
      'Bond enthalpy and lattice enthalpy (Born-Haber)',
      'Entropy, spontaneity and second law',
      'Gibbs energy change and equilibrium constant relation',
    ],
    'Equilibrium': [
      'Law of mass action, Kp and Kc relations',
      'Le Chateliers principle and factors affecting equilibrium',
      'Ionic equilibrium — strong and weak electrolytes',
      'Ostwald dilution law and degree of ionisation',
      'pH, pOH and pKa calculations',
      'Common ion effect and solubility product',
      'Buffer solutions and Henderson equation',
      'Salt hydrolysis and pH of salt solutions',
    ],
    'Solutions': [
      'Concentration terms — molarity, molality, mole fraction, ppm',
      'Raoults law for volatile and non-volatile solutes',
      'Ideal and non-ideal solutions, azeotropes',
      'Colligative properties — RLVP, elevation in Tb, depression in Tf',
      'Osmotic pressure and reverse osmosis',
      "van't Hoff factor, association and dissociation",
    ],
    'Electrochemistry': [
      'Electrolytic and galvanic cells, cell notation',
      'Standard electrode potential and electrochemical series',
      'Nernst equation and EMF of cell',
      'Relation between Gibbs energy, EMF and equilibrium constant',
      'Conductance, molar conductivity and Kohlrausch law',
      'Faradays laws of electrolysis',
      'Batteries, fuel cells and corrosion',
    ],
    'The p-Block Elements (Group 13-14)': [
      'Group trends in electronic configuration and oxidation states',
      'Inert pair effect and anomalous behaviour of B and C',
      'Boron compounds — borax, boric acid, diborane',
      'Allotropes of carbon and catenation',
      'Silicones, silicates and zeolites',
    ],
    'Hydrocarbons': [
      'Alkanes — conformations, preparation and halogenation',
      'Alkenes — addition reactions, Markovnikov and peroxide effect',
      'Alkynes — acidic nature, addition and polymerisation',
      'Aromaticity and Huckel rule',
      'Electrophilic substitution in benzene and directive influence',
      'Ozonolysis and oxidation reactions',
    ],
    'Amines': [
      'Classification, structure and basicity of amines',
      'Preparation — Gabriel phthalimide, Hoffmann bromamide',
      'Reactions with nitrous acid, carbylamine test',
      'Diazonium salts — preparation and coupling reactions',
      'Separation and distinction of 1°, 2°, 3° amines (Hinsberg)',
    ],
    'Biomolecules': [
      'Carbohydrates — classification, glucose and fructose structures',
      'Anomers, mutarotation and glycosidic linkage',
      'Proteins — amino acids, peptide bond, structures, denaturation',
      'Enzymes and mechanism of enzyme action',
      'Vitamins — classification and deficiency diseases',
      'Nucleic acids — DNA, RNA structure and functions',
      'Hormones — overview',
    ],
    'Purification and Characterisation of Organic Compounds': [
      'Crystallisation, sublimation, distillation, chromatography',
      'Qualitative detection of N, S, halogens (Lassaigne test)',
      'Quantitative estimation of C, H, N, S, halogens',
      'Empirical and molecular formula determination',
    ],
    'Principles Related to Practical Chemistry': [
      'Detection of functional groups in organic compounds',
      'Salt analysis — cations and anions',
      'Titrimetric exercises — oxalic acid vs KMnO4, Mohr salt',
      'Preparation of inorganic and organic compounds',
      'Chemistry involved in simple experiments',
    ],
  },
  Mathematics: {
    'Sets, Relations and Functions': [
      'Union, intersection, complement and Venn diagrams',
      'Types of relations — reflexive, symmetric, transitive, equivalence',
      'Domain, codomain, range of functions',
      'One-one, onto and inverse functions, composition',
    ],
    'Matrices and Determinants': [
      'Types of matrices and algebra of matrices',
      'Transpose, symmetric and skew-symmetric matrices',
      'Determinants of order 2 and 3, properties',
      'Area of triangle using determinants',
      'Adjoint and inverse of a matrix',
      'Solution of system of linear equations — consistency, Cramers rule',
      'Elementary row operations and rank-based consistency',
    ],
    'Inverse Trigonometric Functions': [
      'Domain, range and principal value branches',
      'Properties and simplification of inverse trig expressions',
      'Sum and difference formulae for inverse functions',
    ],
    'Integral Calculus': [
      'Standard integrals and integration by substitution',
      'Integration by parts and partial fractions',
      'Integration of trigonometric and irrational functions',
      'Definite integrals and fundamental theorem of calculus',
      'Properties of definite integrals',
      'Definite integral as limit of a sum',
      'Improper and reduction formulae based integrals',
    ],
    'Statistics': [
      'Mean, median, mode of grouped and ungrouped data',
      'Mean deviation about mean and median',
      'Variance and standard deviation',
      'Coefficient of variation and combined variance',
    ],
    'Probability': [
      'Classical and axiomatic probability, sample space',
      'Addition and multiplication theorems',
      'Conditional probability and independence',
      'Bayes theorem and total probability',
      'Random variable, probability distribution, mean and variance',
      'Bernoulli trials and binomial distribution',
    ],
    'Mathematical Reasoning': [
      'Statements, negation, compound statements',
      'Truth tables, tautology and contradiction',
      'Implication, converse and contrapositive',
    ],
    'Differential Calculus — Limits': [
      'Limits of algebraic, trigonometric, exponential, logarithmic functions',
      'L Hopital rule and standard expansions',
      'Continuity at a point and on an interval',
      'Differentiability and relation with continuity',
    ],
    'Circles': [
      'General equation of a circle, centre and radius',
      'Equation of tangent and normal to a circle',
      'Length of tangent, power of a point',
      'Family of circles, radical axis and orthogonality',
      'Position of point and line relative to a circle',
    ],
  },
};

for (const subject of Object.keys(ADDITIONAL)) {
  SYLLABUS[subject] = { ...(SYLLABUS[subject] || {}), ...ADDITIONAL[subject] };
}

export function getTopics(subject: string, chapter: string): string[] {
  return SYLLABUS[subject]?.[chapter] || [];
}

export function chaptersWithTopics(subject: string): string[] {
  return Object.keys(SYLLABUS[subject] || {}).sort((a, b) => a.localeCompare(b));
}

