// JEE/NEET topic-wise syllabus map. subject -> chapter -> topics[].
// Curated from latest JEE/NEET PYQ-relevant micro-topics.

export type SyllabusMap = Record<string, Record<string, string[]>>;

export const SYLLABUS: SyllabusMap = {
  Physics: {
    'Units and Measurements': [
      'Dimensional formulas of physical constants (G, ε₀, μ₀, h)',
      'Principle of Homogeneity and applications',
      'Conversion of units using dimensional analysis',
      'Significant figures and rounding off',
      'Absolute, relative, and percentage error',
      'Combination of errors in sums, products, and powers',
      'Vernier Callipers — least count and zero error',
      'Screw Gauge — pitch and least count',
    ],
    'Motion in a Straight Line': [
      'Instantaneous velocity and acceleration',
      'Kinematic equations for constant acceleration',
      'Analysis of x-t, v-t, a-t graphs',
      'Relative velocity in 1D',
      'Motion under gravity — time of ascent and descent',
    ],
    'Motion in a Plane': [
      'Vector addition, subtraction, and resolution',
      'Dot and Cross products',
      'Projectile motion — time of flight, max height, range',
      'Equation of trajectory and range on inclined plane',
      'Uniform circular motion',
      'Relative velocity — rain-man and river-boat problems',
    ],
    'Laws of Motion': [
      'Newton’s Second Law (F=ma)',
      'Impulse-Momentum Theorem',
      'Conservation of linear momentum',
      'Equilibrium of concurrent forces (Lami’s Theorem)',
      'Free Body Diagrams with pulleys and blocks',
      'Friction — static, limiting, kinetic',
      'Angle of friction and angle of repose',
      'Block on inclined plane with friction',
      'Centripetal and centrifugal forces',
      'Banking of roads and bending of cyclist',
    ],
    'Work, Energy and Power': [
      'Work done by constant and variable forces',
      'Kinetic energy and Work-Energy Theorem',
      'Gravitational and Spring PE',
      'Conservation of mechanical energy',
      'Instantaneous and average power',
      'Elastic and inelastic collisions in 1D and 2D',
      'Coefficient of restitution',
    ],
    'System of Particles and Rotational Motion': [
      'Centre of mass — discrete and continuous systems',
      'Motion of COM and conservation of momentum',
      'Torque and angular momentum (L=Iω)',
      'Parallel and perpendicular axis theorems',
      'MOI of standard bodies (ring, disc, rod, sphere, cylinder)',
      'Radius of gyration',
      'Rolling motion — KE and acceleration on incline',
    ],
    Gravitation: [
      'Newton’s Law of Gravitation (vector form)',
      'Variation of g with altitude, depth, rotation',
      'Gravitational PE and gravitational potential',
      'Escape velocity and orbital velocity',
      'Kepler’s laws of planetary motion',
    ],
    'Mechanical Properties of Solids': [
      'Stress-strain curve and Hooke’s Law',
      'Young’s, Bulk and Rigidity moduli',
      'Elastic PE in a stretched wire',
    ],
    'Mechanical Properties of Fluids': [
      'Pascal’s Law and Hydraulic Lift',
      'Variation of pressure with depth and Buoyancy',
      'Viscosity — Stokes Law and terminal velocity',
      'Bernoulli’s Principle — Venturimeter, Torricelli',
      'Surface Tension — excess pressure in drops, capillary rise',
    ],
    'Thermal Properties of Matter': [
      'Linear, areal and volumetric thermal expansion',
      'Specific heat capacity and calorimetry',
      'Latent heat and phase changes',
      'Heat transfer — conduction, convection, radiation',
    ],
    Thermodynamics: [
      'Zeroth and First Law of Thermodynamics',
      'Isothermal, adiabatic, isobaric and isochoric processes',
      'Cp, Cv and their relation',
      'Heat engines and efficiency',
      'Refrigerators and COP',
      'Carnot cycle',
      'Second law and entropy basics',
    ],
    'Kinetic Theory of Gases': [
      'Ideal gas equation and assumptions',
      'Mean, RMS and most probable speeds',
      'Degrees of freedom and equipartition of energy',
      'Mean free path',
    ],
    Oscillations: [
      'SHM — displacement, velocity, acceleration',
      'Energy in SHM',
      'Spring oscillations and series/parallel combinations',
      'Simple pendulum and physical pendulum',
      'Damped and forced oscillations, resonance',
    ],
    Waves: [
      'Transverse and longitudinal waves',
      'Speed of waves on a string and in gases',
      'Superposition, interference and standing waves',
      'Beats and beat frequency',
      'Doppler effect',
    ],
    'Electric Charges and Fields': [
      'Coulomb’s Law and superposition',
      'Electric field due to point charges, dipoles and continuous distributions',
      'Gauss’s Law and applications (sphere, cylinder, plane)',
      'Electric flux',
    ],
    'Electrostatic Potential and Capacitance': [
      'Electric potential and PE of a system',
      'Equipotential surfaces',
      'Capacitor — parallel plate, with dielectric',
      'Series/parallel combinations of capacitors',
      'Energy stored in a capacitor',
    ],
    'Current Electricity': [
      'Ohm’s Law, drift velocity, mobility',
      'Resistivity and temperature dependence',
      'Kirchhoff’s laws and Wheatstone bridge',
      'Meter bridge and potentiometer',
      'Cells — EMF, internal resistance, combinations',
    ],
    'Moving Charges and Magnetism': [
      'Magnetic force on moving charge — Lorentz force',
      'Biot-Savart Law and Ampere’s Law',
      'Magnetic field due to a straight wire, loop, solenoid',
      'Cyclotron',
      'Force between parallel currents',
      'Galvanometer — conversion to ammeter and voltmeter',
    ],
    'Magnetism and Matter': [
      'Bar magnet and magnetic dipole moment',
      'Earth’s magnetism',
      'Dia-, para-, and ferromagnetism',
      'Hysteresis loop',
    ],
    'Electromagnetic Induction': [
      'Faraday’s Law and Lenz’s Law',
      'Motional EMF',
      'Self and mutual induction',
      'Energy stored in an inductor',
      'Eddy currents',
    ],
    'Alternating Current': [
      'AC circuits — R, L, C and combinations',
      'Phasors and impedance',
      'LCR series resonance',
      'Power in AC, power factor',
      'Transformer',
    ],
    'Electromagnetic Waves': [
      'Maxwell’s equations (qualitative)',
      'EM wave properties and energy',
      'EM spectrum and applications',
    ],
    'Ray Optics and Optical Instruments': [
      'Reflection at spherical mirrors — mirror formula',
      'Refraction and Snell’s Law',
      'Total internal reflection and applications',
      'Lens formula and lensmaker’s equation',
      'Combination of lenses, power',
      'Prism — dispersion and angular deviation',
      'Microscope and telescope',
    ],
    'Wave Optics': [
      'Huygens’ principle',
      'Young’s double slit experiment',
      'Single slit diffraction',
      'Polarisation — Brewster’s law, Malus’ law',
    ],
    'Dual Nature of Radiation and Matter': [
      'Photoelectric effect and Einstein’s equation',
      'de Broglie wavelength',
      'Davisson-Germer experiment',
    ],
    Atoms: [
      'Bohr model — energy levels and spectra',
      'Hydrogen spectrum series',
      'Rutherford scattering',
    ],
    Nuclei: [
      'Mass defect and binding energy per nucleon',
      'Radioactivity — α, β, γ decay',
      'Half-life and mean life',
      'Nuclear fission and fusion',
    ],
    'Semiconductor Electronics': [
      'Energy bands — metals, insulators, semiconductors',
      'P-N junction — forward and reverse bias',
      'Diode as rectifier (half and full wave)',
      'Logic gates — OR, AND, NOT, NAND, NOR',
    ],
  },
  Chemistry: {
    'Some Basic Concepts of Chemistry': [
      'Mole concept, stoichiometry, limiting reagent',
      'Concentration terms — molarity, molality, normality, mole fraction',
      'Empirical and molecular formula',
    ],
    'Structure of Atom': [
      'Quantum numbers (n, l, m, s)',
      'Electronic configuration — Aufbau, Pauli, Hund’s Rule',
      'Bohr model and hydrogen spectrum',
      'de Broglie wavelength and Heisenberg’s uncertainty',
    ],
    'Classification of Elements and Periodicity': [
      'Trends in atomic and ionic radius',
      'Ionisation enthalpy and electron gain enthalpy',
      'Electronegativity trends',
      'Diagonal relationship',
    ],
    'Chemical Bonding and Molecular Structure': [
      'VSEPR theory — molecular geometry',
      'Hybridisation (sp, sp², sp³, sp³d, sp³d²)',
      'Molecular Orbital Theory — bond order, magnetic behavior',
      'Hydrogen bonding',
      'Resonance and formal charge',
    ],
    'States of Matter': [
      'Ideal gas equation and Dalton’s Law',
      'Real gases — van der Waals equation',
      'Critical phenomena',
    ],
    'Thermodynamics (Chemistry)': [
      'First Law — enthalpy and internal energy',
      'Hess’s Law',
      'Entropy and Gibbs free energy (ΔG) for spontaneity',
      'Bond enthalpy and lattice energy',
    ],
    Equilibrium: [
      'Law of mass action — Kp and Kc',
      'Le Chatelier’s Principle',
      'Ionic equilibrium — pH, buffer solutions',
      'Solubility product (Ksp)',
      'Acid–base concepts',
    ],
    'Redox Reactions': [
      'Oxidation number rules',
      'Balancing redox reactions (oxidation number / half-reaction)',
      'Standard electrode potentials',
    ],
    Solutions: [
      'Raoult’s Law and ideal/non-ideal solutions',
      'Colligative properties',
      'Van’t Hoff factor',
      'Abnormal molecular mass',
    ],
    Electrochemistry: [
      'Nernst equation',
      'Electrochemical series',
      'Faraday’s Laws of Electrolysis',
      'Molar conductivity and Kohlrausch’s law',
      'Galvanic and electrolytic cells',
    ],
    'Chemical Kinetics': [
      'Order and molecularity',
      'First order — integrated rate law and half-life',
      'Arrhenius equation and activation energy',
      'Effect of catalyst and temperature',
    ],
    'The p-Block Elements (Group 15-18)': [
      'Oxoacids of phosphorus, sulphur, halogens',
      'Allotropes and anomalous behavior',
      'Interhalogens and noble gas compounds',
    ],
    'The d- and f-Block Elements': [
      'Lanthanoid contraction',
      'Variable oxidation states',
      'Magnetic properties and color',
      'KMnO₄ and K₂Cr₂O₇ — preparation and reactions',
    ],
    'Coordination Compounds': [
      'IUPAC nomenclature of complexes',
      'Isomerism — geometrical, optical, ionisation, linkage',
      'Crystal Field Theory — splitting in octahedral and tetrahedral fields',
      'Stability of complexes',
    ],
    'Organic Chemistry — Basic Principles & Techniques': [
      'Inductive, resonance and hyperconjugation effects',
      'Stability of carbocations, carbanions and free radicals',
      'Nucleophilic vs electrophilic substitution mechanisms',
      'Methods of purification of organic compounds',
    ],
    Hydrocarbons: [
      'Alkanes — preparation and reactions',
      'Markovnikov and anti-Markovnikov addition',
      'Alkynes — acidity and reactions',
      'Aromatic hydrocarbons — electrophilic substitution',
    ],
    'Haloalkanes and Haloarenes': [
      'SN1 and SN2 mechanisms',
      'Elimination reactions — E1, E2',
      'Reactions of haloarenes',
    ],
    'Alcohols, Phenols and Ethers': [
      'Reimer-Tiemann reaction',
      'Kolbe’s reaction',
      'Williamson ether synthesis',
      'Acidity of alcohols vs phenols',
    ],
    'Aldehydes, Ketones and Carboxylic Acids': [
      'Aldol condensation',
      'Cannizzaro reaction',
      'Wittig and Clemmensen reactions',
      'Acidity of carboxylic acids',
    ],
    Amines: [
      'Hoffmann bromamide degradation',
      'Carbylamine reaction',
      'Diazonium salts and reactions',
      'Basicity of amines',
    ],
    Biomolecules: [
      'Glucose — open chain and cyclic structure',
      'Amino acids — zwitterion, peptide bond',
      'DNA and RNA — bases and structure',
    ],
  },
  Mathematics: {
    'Sets': ['Types of sets', 'Operations on sets', 'Venn diagrams'],
    'Relations and Functions': [
      'Types of relations — equivalence',
      'Composite functions and inverse functions',
      'Domain, range, and graphs',
    ],
    'Trigonometric Functions': [
      'Trig identities and equations',
      'Inverse trigonometric functions basics',
      'Heights and distances',
    ],
    'Complex Numbers and Quadratic Equations': [
      'Argand plane and modulus-argument form',
      'Euler’s form and De Moivre’s theorem',
      'Cube roots of unity',
      'Location of roots and common roots',
    ],
    'Permutations and Combinations': [
      'Linear and circular arrangements',
      'Combinations with restrictions',
      'Derangements',
    ],
    'Binomial Theorem': [
      'General term and middle term',
      'Independent term',
      'Properties of binomial coefficients',
    ],
    'Sequences and Series': [
      'AP, GP, HP and AGP',
      'AM-GM-HM inequality',
      'Summation of special series (Σn, Σn², Σn³)',
    ],
    'Straight Lines': [
      'Distance between parallel lines',
      'Family of lines',
      'Angle bisectors',
    ],
    'Conic Sections': [
      'Parabola — focal chord, latus rectum',
      'Ellipse — eccentricity, director circle',
      'Hyperbola — asymptotes, conjugate hyperbola',
    ],
    'Limits and Derivatives': [
      'Standard limits and L’Hopital’s Rule',
      'Differentiation rules and chain rule',
      'Logarithmic differentiation',
    ],
    Probability: [
      'Conditional probability',
      'Bayes’ theorem',
      'Bernoulli trials and binomial distribution',
    ],
    Matrices: [
      'Types of matrices and operations',
      'Inverse by adjoint method',
      'Elementary row operations',
    ],
    Determinants: [
      'Properties of determinants',
      'Cramer’s Rule',
      'Area of triangle and consistency of equations',
    ],
    'Continuity and Differentiability': [
      'Continuity at a point and on an interval',
      'Differentiability and chain rule',
      'Rolle’s and Mean Value theorems',
    ],
    'Application of Derivatives': [
      'Tangents and normals',
      'Maxima and minima',
      'Increasing/decreasing functions',
      'Approximations',
    ],
    Integrals: [
      'Integration by substitution',
      'Integration by parts',
      'Integration using partial fractions',
      'Properties of definite integrals',
      'Leibnitz Rule',
    ],
    'Application of Integrals': [
      'Area under curves',
      'Area between two curves',
    ],
    'Differential Equations': [
      'Variable separable',
      'Linear differential equations',
      'Homogeneous differential equations',
    ],
    'Vector Algebra': [
      'Dot and cross products',
      'Scalar and vector triple products',
      'Applications to geometry',
    ],
    'Three Dimensional Geometry': [
      'Direction cosines and ratios',
      'Equation of line and plane',
      'Shortest distance between skew lines',
      'Angle between two planes',
    ],
  },
  Biology: {
    'Biological Classification': [
      'Monera — characteristics and examples',
      'Protista — characteristics and examples',
      'Fungi — classification and reproduction',
      'Five kingdom classification',
    ],
    'Animal Kingdom': [
      'Non-chordates — classification with examples',
      'Chordates — classification up to class',
      'Salient features and distinguishing characters',
    ],
    'Anatomy of Flowering Plants': [
      'Tissue systems — epidermal, ground, vascular',
      'Anatomy of dicot and monocot stem',
      'Secondary growth in dicot stems',
    ],
    'Cell Cycle and Cell Division': [
      'Phases of cell cycle',
      'Mitosis — stages and significance',
      'Meiosis — Prophase I sub-stages',
    ],
    'Principles of Inheritance and Variation': [
      'Mendel’s laws',
      'Dihybrid cross and test cross',
      'Pedigree analysis',
      'Chromosomal disorders',
    ],
    'Molecular Basis of Inheritance': [
      'DNA replication',
      'Transcription — promoter and terminator',
      'Translation and genetic code',
      'Lac operon',
    ],
    'Body Fluids and Circulation': [
      'Cardiac cycle',
      'ECG waves',
      'Double circulation',
      'Blood groups and clotting',
    ],
    'Excretory Products and Their Elimination': [
      'Mechanism of urine formation',
      'Counter-current mechanism',
      'Regulation of kidney function',
    ],
    'Neural Control and Coordination': [
      'Nerve impulse conduction',
      'Reflex arc',
      'Synapse and synaptic transmission',
    ],
    'Photosynthesis in Higher Plants': [
      'Cyclic and non-cyclic photophosphorylation',
      'C3 vs C4 pathway',
      'Photorespiration',
      'Factors affecting photosynthesis',
    ],
    'Respiration in Plants': [
      'Glycolysis',
      'Krebs cycle',
      'Electron transport system',
      'Respiratory quotient',
    ],
    'Organisms and Populations': [
      'Mutualism, competition and predation',
      'Population growth models',
      'Population attributes',
    ],
    Ecosystem: [
      'Energy flow in ecosystem',
      'Ecological pyramids',
      'Nutrient cycling — carbon and phosphorus',
    ],
    'Biodiversity and Conservation': [
      'In-situ and ex-situ conservation',
      'Hotspots of biodiversity',
      'IUCN red list categories',
    ],
  },
};

export function getTopics(subject: string, chapter: string): string[] {
  return SYLLABUS[subject]?.[chapter] || [];
}

export function chaptersWithTopics(subject: string): string[] {
  return Object.keys(SYLLABUS[subject] || {});
}
